sudo: false
language: python

services:
  - postgresql

cache:
  directories:
    - $HOME/.cache/pip/wheels

python:
  - "3.5"

env:
  - LDFLAGS=-L$HOME/.local/lib CFLAGS=-I$HOME/.local/include LD_LIBRARY_PATH=$HOME/.local/lib TERVIS_SKIP_LIBTERVIS_DEP=1

install:
  - (cd /tmp && wget https://github.com/edenhill/librdkafka/archive/0.9.1.tar.gz && tar -xzf ./0.9.1.tar.gz && cd librdkafka-0.9.1 && ./configure --prefix=$HOME/.local && make && make install)
  - pip install flake8
  - pip install git+https://github.com/getsentry/sentry-libhealth
  - pip install --editable .

before_script:
  - psql -c 'create database sentry_health_test' -U postgres

script:
  - make lint test-light
